services:
  api:
    build: .
    restart: always
    init: true
    ports:
      - 80:$PORT
    environment:
      - LOG_LEVEL
      - LOG_FORMAT
      - HOST
      - PORT
      - TYPE
      - PROJECT_ID
      - PRIVATE_KEY_ID
      - PRIVATE_KEY
      - CLIENT_EMAIL
      - CLIENT_ID
      - AUTH_URI
      - TOKEN_URI
      - AUTH_PROVIDER_X509_CERT_URL
      - CLIENT_X509_CERT_URL
      - UNIVERSE_DOMAIN
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
      - KAKAO_API_KEY
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_DATABASE
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
