services:
  api:
    build: .
    restart: always
    ports:
      - 80:$PORT
    environment:
      - HOST
      - PORT
      - JWT_SECRET
      - JWT_EXPIRY
      - PEPPER
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
  db:
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_DATABASE
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
