services:
  api:
    image: reg/api
    restart: always
    ports:
      - 80:3330
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE=${DATABASE}
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d/
        read_only: true
volumes:
  db:
