services:
  api:
    build: .
    restart: always
    init: true
    ports:
      - 80:$PORT
    environment:
      - HOST
      - PORT
      - JWT_SECRET
      - JWT_EXPIRY
      - PEPPER
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
  db:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_DATABASE
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
