name: Deploy to ECR
on:
  push:
    branches:
      - dev
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - uses: benjlevesque/short-sha@v3.0
        id: sha
      - name: Generate tag for the current build
        run: echo "REV_TAG=$(date +%Y.%m.%d-%H.%M.%S)-${{ steps.sha.outputs.sha }}" >> $GITHUB_ENV
      - name: Build and push to ECR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags:
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:$REV_TAG
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
